# Generated by Django 4.0.4 on 2022-05-12 02:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def populate_section(apps, schemaeditor):
    sections = [

        {
            'name' : 'FrontPage',
            'description' : 'Mega Import stuff'
        },
        {
            'name' : 'Sports',
            'description' : 'super in shape people do sports'
        },
        {
            'name' : 'Society',
            'description' : "people you don't care about doing things no one cares about"
        },
        {
            'name' : 'Business',
            'description' : 'consumers and companies buying and selling things and such'
        },
    ]

    Section = apps.get_model('articles', 'Section')
    for x in sections:
        section = Section(name = x['name'], description = x['description'])
        section.save()

class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('description', models.TextField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('body', models.TextField(max_length=2000)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to=settings.AUTH_USER_MODEL)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='articles.section')),
            ],
        ),
        migrations.RunPython(populate_section)

    ]
