# Generated by Django 4.0.4 on 2022-05-12 00:44

from django.db import migrations, models
import django.db.models.deletion


def populate_language(apps, schemaeditor):
    language_types = [
        {
            "key" : "EN",
            "name" : "English"
        },
        {
            "key" : "ES",
            "name" : "Spanish"
        },
        {
            "key" : "DE",
            "name" : "Deutsch"
        },
        {
            "key" : "PT",
            "name" : "Portugues"
        },
    ]

    Language = apps.get_model('accounts', 'Language')
    for x in language_types:
        language = Language(key = x['key'], name = x['name'])
        language.save()


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=4)),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.AddField(
            model_name='customuser',
            name='preferred_language',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.language'),
        ),
        migrations.RunPython(populate_language)

    ]
